// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020

package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/esrid/back-office-kit/ui/marketing"

// Inline SVG data URIs: the gallery must stay self-contained, so no external
// image host.
const heroVisual = "data:image/svg+xml;utf8," +
	"%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 480 300'%3E" +
	"%3Crect width='480' height='300' rx='10' fill='%234f39f6' opacity='0.08'/%3E" +
	"%3Crect x='24' y='24' width='170' height='14' rx='7' fill='%234f39f6' opacity='0.45'/%3E" +
	"%3Crect x='24' y='54' width='300' height='10' rx='5' fill='%234f39f6' opacity='0.22'/%3E" +
	"%3Crect x='24' y='96' width='432' height='60' rx='8' fill='%234f39f6' opacity='0.14'/%3E" +
	"%3Crect x='24' y='170' width='432' height='60' rx='8' fill='%234f39f6' opacity='0.14'/%3E" +
	"%3Crect x='24' y='244' width='210' height='32' rx='8' fill='%234f39f6' opacity='0.5'/%3E" +
	"%3C/svg%3E"

func logo(nom string) marketing.Image {
	svg := "data:image/svg+xml;utf8," +
		"%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 28'%3E" +
		"%3Ctext x='0' y='20' font-family='sans-serif' font-size='18' font-weight='600' fill='currentColor'%3E" +
		nom + "%3C/text%3E%3C/svg%3E"
	return marketing.Image{Src: svg, Alt: nom, Width: 120, Height: 28}
}

func demoHero() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = marketing.Hero(marketing.HeroProps{
			Eyebrow:  "Back-office",
			Title:    "Pilotez vos opérations sans perdre le fil",
			Subtitle: "Utilisateurs, facturation et audit réunis dans un espace conçu pour les équipes qui traitent des centaines de dossiers par jour.",
			Actions: []marketing.Action{
				{Label: "Essayer gratuitement", Href: "/signup", Primary: true},
				{Label: "Voir une démo", Href: "/demo"},
			},
			Note:   "Sans carte bancaire · 14 jours",
			Visual: marketing.Image{Src: heroVisual, Alt: "Aperçu du tableau de bord", Width: 480, Height: 300},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func demoFeatures() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = marketing.FeatureGrid("Ce que vous y gagnez", "Trois choses que les équipes remarquent la première semaine.", []marketing.Feature{
			{Title: "Tout est une URL", Description: "Un filtre, un tri, une page : chaque état se partage par lien et se retrouve au rechargement."},
			{Title: "Rien à installer", Description: "Rendu côté serveur. Pas de build client, pas d'attente au premier écran."},
			{Title: "Audit intégré", Description: "Chaque action laisse une trace nominative, consultable sans quitter la fiche."},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func demoPricing() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = marketing.PricingTable("Tarifs", "Changez de palier quand vos volumes changent, pas avant.", []marketing.Plan{
			{Name: "Essentiel", Price: "29 €", Period: "par mois", Description: "Pour une équipe qui démarre.",
				Features: []string{"3 utilisateurs", "10 000 enregistrements", "Journal d'audit 30 jours"},
				Action:   marketing.Action{Label: "Commencer", Href: "/signup?plan=essentiel"}},
			{Name: "Équipe", Price: "89 €", Period: "par mois", Description: "Le palier le plus choisi.", Highlighted: true, Badge: "Populaire",
				Features: []string{"15 utilisateurs", "Enregistrements illimités", "Journal d'audit 1 an", "Vues enregistrées"},
				Action:   marketing.Action{Label: "Commencer", Href: "/signup?plan=equipe"}},
			{Name: "Entreprise", Price: "Sur devis", Description: "Contraintes de conformité, hébergement dédié.",
				Features: []string{"Utilisateurs illimités", "SSO SAML", "Rétention sur mesure", "Support dédié"},
				Action:   marketing.Action{Label: "Nous contacter", Href: "/contact"}},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func demoTestimonials() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = marketing.TestimonialGrid("Ils l'utilisent tous les jours", []marketing.Quote{
			{Text: "On a supprimé trois tableurs partagés la première semaine. L'équipe support ne demande plus d'export.", Author: "Amélie Rousseau", Role: "Responsable opérations, Acme"},
			{Text: "Le journal d'audit a réglé une discussion de six mois avec notre auditeur en une capture d'écran.", Author: "Nora Martin", Role: "DAF, Kelvin"},
			{Text: "Nos écrans se chargent plus vite que notre ancien back-office alors qu'on affiche cinq fois plus de lignes.", Author: "Bruno Keller", Role: "CTO, Partner.io"},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func demoFAQ() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = marketing.FAQ("Questions fréquentes", []marketing.QA{
			{Question: "Puis-je changer de palier en cours de mois ?", Answer: "Oui. Le changement prend effet immédiatement et la facture suivante est calculée au prorata."},
			{Question: "Que se passe-t-il à la fin de l'essai ?", Answer: "Le compte passe en lecture seule. Rien n'est supprimé, et vos données restent exportables pendant 90 jours."},
			{Question: "Hébergez-vous les données en Europe ?", Answer: "Oui, à Paris et à Francfort. Le palier Entreprise permet de choisir une région unique."},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func demoCTA() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = marketing.CTASection(
			"Essayez sur vos vraies données",
			"Importez un export CSV et regardez à quoi ressemblent vos écrans en quinze minutes.",
			[]marketing.Action{
				{Label: "Créer un compte", Href: "/signup", Primary: true},
				{Label: "Parler à quelqu'un", Href: "/contact"},
			},
			"Aucune carte bancaire demandée.",
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func demoLogos() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var7 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var7 == nil {
			templ_7745c5c3_Var7 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = marketing.LogoCloud("Ils nous font confiance", []marketing.Image{
			logo("Acme"), logo("Kelvin"), logo("Partner"), logo("Nord"), logo("Vela"),
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func demoFooter() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var8 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var8 == nil {
			templ_7745c5c3_Var8 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = marketing.MarketingFooter("Acme Admin", "Le back-office des équipes qui traitent beaucoup de dossiers.", []marketing.FooterColumn{
			{Title: "Produit", Links: []marketing.Action{{Label: "Fonctionnalités", Href: "/features"}, {Label: "Tarifs", Href: "/pricing"}, {Label: "Nouveautés", Href: "/changelog"}}},
			{Title: "Ressources", Links: []marketing.Action{{Label: "Documentation", Href: "/docs"}, {Label: "Statut", Href: "/status"}}},
			{Title: "Société", Links: []marketing.Action{{Label: "À propos", Href: "/about"}, {Label: "Mentions légales", Href: "/legal"}}},
		}, "© 2026 Acme SAS · Hébergé en France").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
