package main

func tier3Sections() []Section {
	return []Section{
		{Group: "Tier 3 — Workflows", ID: "selectable-table", Title: "SelectableDataTable", Purpose: "Sélection serveur, select-all et actions groupées dans un tableau typé.", Uses: []string{"table", "checkbox", "BulkActionBar"}, Demo: demoSelectableTable(), Snippet: `@ui.SelectableDataTable("members", cols, users, q, rowKey, selection, nil)`, Note: "Les cases sont de vrais champs de formulaire. Sans JavaScript, Actualiser la sélection soumet l'état ; Unpoly échange seulement le tableau."},
		{Group: "Tier 3 — Workflows", ID: "row-actions", Title: "RowActionMenu", Purpose: "Actions secondaires et destructives compactées au bout d'une ligne.", Uses: []string{"details", "dropdown", "menu"}, Demo: demoRowActions(), Snippet: `@ui.RowActionMenu("row-actions-"+user.ID, "Actions pour "+user.Name, actions)`, Note: "details/summary garde le menu ouvrable au clavier et sans JavaScript. Les actions portant une Method sont des boutons submit rattachés par [form] au formulaire du menu : un changement d'état ne doit pas passer par un GET, que http.CrossOriginProtection laisse toujours passer. L'id doit être unique par ligne."},
		{Group: "Tier 3 — Workflows", ID: "combobox", Title: "ComboboxField", Purpose: "Autocomplete natif avec suggestions rendues ou rafraîchies par le serveur.", Uses: []string{"datalist", "up-validate"}, Demo: demoCombobox(), Snippet: `@ui.ComboboxField(ui.ComboboxProps{Field: field, Options: matches, SearchTarget: "#f-company-field"})`, Note: "Le datalist est le socle sans JS. SearchTarget permet au serveur de remplacer les suggestions pendant la saisie avec un délai par défaut de 250 ms."},
		{Group: "Tier 3 — Workflows", ID: "saved-views", Title: "SavedViewBar", Purpose: "Rappeler des combinaisons nommées de filtres, tri et colonnes.", Uses: []string{"join", "URL presets"}, Demo: demoSavedViews(), Snippet: `@ui.SavedViewBar(views, currentURL, "/views/new")`, Note: "Une vue est une URL, donc elle reste partageable, ouvrable dans un autre onglet et indépendante d'un store client."},
		{Group: "Tier 3 — Workflows", ID: "async-state", Title: "AsyncState", Purpose: "Un contrat unique pour loading, empty, error, stale et ready.", Uses: []string{"skeleton", "alert", "aria-busy"}, Demo: demoAsyncStates(), Snippet: `@ui.AsyncState(ui.AsyncStateProps{ID: "report", Status: ui.ResourceLoading})`, Note: "Les états ont leur sémantique d'annonce et le retry cible le même fragment. Le contenu stale reste visible au lieu de disparaître."},
		{Group: "Tier 3 — Workflows", ID: "inline-edit", Title: "InlineEdit", Purpose: "Passer d'une valeur à son formulaire puis enregistrer ou annuler sur place.", Uses: []string{"up-target", "up-submit"}, Demo: demoInlineEdit(), Snippet: `@ui.InlineEdit(props, displayValue()) { @ui.Field(field) }`, Note: "Le serveur décide si le fragment est en mode lecture ou édition et renvoie les erreurs dans le même identifiant stable."},
		{Group: "Tier 3 — Workflows", ID: "confirm-action", Title: "ConfirmAction", Purpose: "Confirmation stylée pour les opérations irréversibles, avec friction optionnelle.", Uses: []string{"modal", "up-layer", "validation"}, Demo: demoConfirmAction(), Snippet: `@ui.ConfirmAction(trigger) · @ui.ConfirmDialog(title, message, label, action, "delete", record.Name)`, Note: "La valeur tapée est toujours validée côté serveur. La modal ne remplace jamais l'autorisation ou la vérification métier."},
		{Group: "Tier 3 — Workflows", ID: "wizard", Title: "Wizard", Purpose: "Formulaire multi-étapes dont chaque étape possède sa route et sa validation.", Uses: []string{"steps", "form", "up-submit"}, Demo: demoWizard(), Snippet: `@ui.Wizard(ui.WizardProps{Steps: steps, Current: 1, Action: "/onboarding/company"}) { ... }`, Note: "Les étapes terminées sont des liens serveur. Recharger la page ou revenir en arrière ne perd pas la progression."},
		{Group: "Tier 3 — Workflows", ID: "repeater", Title: "RepeaterField", Purpose: "Ajouter et retirer des lignes imbriquées sans confier leur index au navigateur.", Uses: []string{"fieldset", "formaction"}, Demo: demoRepeater(), Snippet: `@ui.RepeaterField("contacts", "Contacts", rows, "/contacts/add")`, Note: "Chaque ajout ou retrait re-rend le fieldset complet : les noms, index et erreurs restent cohérents avec le modèle serveur."},
		{Group: "Tier 3 — Workflows", ID: "job-progress", Title: "JobProgress", Purpose: "Suivre import, export ou rapport jusqu'à un état terminal.", Uses: []string{"progress", "up-poll"}, Demo: demoJobs(), Snippet: `@ui.JobProgress(ui.JobProgressProps{ID: "export", Status: ui.JobRunning, PollSource: "/jobs/42"})`, Note: "Le polling s'arrête naturellement quand la réponse terminale n'émet plus up-poll. Un ETag peut éviter de transférer un fragment inchangé."},
		{Group: "Tier 3 — Workflows", ID: "notification-center", Title: "NotificationCenter", Purpose: "Compteur non-lu et liste de notifications reliées aux records concernés.", Uses: []string{"details", "list", "badge"}, Demo: demoNotifications(), Snippet: `@ui.NotificationCenter(notifications, "/notifications", false)`, Note: "Le résumé annonce le nombre non lu. Les notifications sont des liens normaux et la dropdown accepte une largeur mobile contrainte."},
	}
}
