// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020

package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/esrid/back-office-kit/ui"

func demoPermissionMatrix() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = ui.PermissionMatrix(ui.PermissionMatrixProps{
			ID: "demo-permissions", Title: "Rôle Opérations", Description: "Capacités effectives pour l’espace Caraïbes.",
			Action: "/roles/operations/permissions", RoleID: "role_ops", RoleVersion: "17",
			Columns: []ui.PermissionColumn{
				{Key: "read", Label: "Lire", Description: "Consulter"},
				{Key: "write", Label: "Modifier", Description: "Créer et éditer"},
				{Key: "delete", Label: "Supprimer", Description: "Action sensible"},
			},
			Rows: []ui.PermissionRow{
				{Resource: "accounts", Label: "Comptes", Description: "Clients et statuts", Cells: []ui.PermissionCell{
					{Permission: "accounts:read", Granted: true, Mutable: false, Inherited: true, Origin: "Membre"},
					{Permission: "accounts:write", Granted: true, Mutable: true},
					{Permission: "accounts:delete", Mutable: true},
				}},
				{Resource: "billing", Label: "Facturation", Description: "Factures et paiements", Cells: []ui.PermissionCell{
					{Permission: "billing:read", Granted: true, Mutable: false, Inherited: true, Origin: "Membre"},
					{Permission: "billing:write", Mutable: true},
					{Permission: "billing:delete", Mutable: false, Reason: "Réservée aux administrateurs"},
				}},
				{Resource: "exports", Label: "Exports", Description: "Données hors plateforme", Cells: []ui.PermissionCell{
					{Permission: "exports:read", Granted: true, Mutable: true},
					{Permission: "exports:write", Mutable: true},
					{Permission: "exports:delete", Mutable: false, Reason: "Non applicable"},
				}},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func demoAccessGrants() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = ui.AccessGrantList(ui.AccessGrantListProps{
			ID: "demo-grants", Title: "Accès directs", Description: "Exceptions accordées en dehors des rôles.",
			Action: "/access/grants", Version: "9", CreateHref: "/access/grants/new",
			Items: []ui.AccessGrant{
				{ID: "grant_81", Subject: "Amélie Rousseau", SubjectHref: "/users/amelie", Kind: "Utilisateur", Permission: "Modifier", Scope: "Compte Acme Caraïbes", GrantedBy: "Nora Martin", GrantedAt: "aujourd’hui à 09:12", GrantedDatetime: "2026-08-25T09:12:00-04:00", ExpiresAt: "dans 6 jours", ExpiresDatetime: "2026-08-31T23:59:00-04:00", Revocable: true},
				{ID: "grant_52", Subject: "Équipe Finance", Kind: "Équipe", Permission: "Lire", Scope: "Toutes les factures", GrantedBy: "Politique finance-read", GrantedAt: "le 4 juin", GrantedDatetime: "2026-06-04", Revocable: false},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func demoSessionManager() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = ui.SessionManager(ui.SessionManagerProps{
			ID: "demo-sessions", Title: "Sessions d’Amélie", Description: "3 appareils ont accès à ce compte.",
			Action: "/security/sessions", SubjectID: "usr_42", Version: "12", CanRevokeAll: true,
			Sessions: []ui.SecuritySession{
				{ID: "sess_current", Device: "MacBook Pro", Browser: "Safari 20 · macOS", Location: "Fort-de-France, MQ", IP: "192.0.2.41", LastSeen: "maintenant", LastSeenDatetime: "2026-08-25T15:20:00-04:00", Current: true},
				{ID: "sess_phone", Device: "iPhone 18", Browser: "Safari Mobile", Location: "Le Lamentin, MQ", IP: "192.0.2.84", LastSeen: "il y a 2 heures", LastSeenDatetime: "2026-08-25T13:18:00-04:00", Revocable: true},
				{ID: "sess_old", Device: "Windows PC", Browser: "Chrome 141 · Windows", Location: "Paris, FR", IP: "198.51.100.7", LastSeen: "il y a 12 jours", LastSeenDatetime: "2026-08-13T10:04:00+02:00", Revocable: true},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func demoAPIKeyManager() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = ui.APIKeyManager(ui.APIKeyManagerProps{
			ID: "demo-api-keys", Title: "Clés d’API", Description: "Identifiants de service pour les intégrations.",
			Action: "/security/api-keys", Version: "6", CreateHref: "/security/api-keys/new",
			Keys: []ui.APIKey{
				{ID: "key_prod", Name: "Synchronisation comptable", Prefix: "bok_live_a91f", Scopes: []string{"invoices:read", "payments:write"}, CreatedAt: "le 2 juillet", CreatedDatetime: "2026-07-02", LastUsed: "il y a 4 minutes", LastUsedDatetime: "2026-08-25T15:16:00-04:00", ExpiresAt: "dans 97 jours", ExpiresDatetime: "2026-11-30", Status: ui.APIKeyActive, Revocable: true},
				{ID: "key_import", Name: "Ancien import CRM", Prefix: "bok_live_30ce", Scopes: []string{"contacts:write"}, CreatedAt: "le 8 janvier", CreatedDatetime: "2026-01-08", LastUsed: "il y a 43 jours", LastUsedDatetime: "2026-07-13", ExpiresAt: "dans 5 jours", ExpiresDatetime: "2026-08-30", Status: ui.APIKeyExpiring, Revocable: true},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func demoSecretReveal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = ui.SecretReveal(ui.SecretRevealProps{
			ID: "demo-secret", Name: "Synchronisation comptable", Secret: "bok_live_R4nd0mExampleValue_91f2", SecretID: "secret_91f2",
			CreatedAt: "à l’instant", CreatedDatetime: "2026-08-25T15:20:00-04:00", AcknowledgeAction: "/security/api-keys/ack",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func demoStepUpAuth() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex justify-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.StepUpAuthCard(ui.StepUpAuthProps{
			ID: "demo-step-up", Title: "Confirmez votre identité", Message: "La révocation de toutes les sessions exige une vérification récente.",
			Action: "/auth/step-up", ChallengeID: "challenge_f912", ChallengeVersion: "2", ExpiresAt: "dans 4 minutes", ExpiresDatetime: "2026-08-25T15:24:00-04:00",
			Method:       ui.StepUpMethod{Value: "totp", Label: "Application d’authentification", Description: "Saisissez le code à 6 chiffres affiché dans votre application.", InputLabel: "Code à 6 chiffres", InputType: "text", Autocomplete: "one-time-code", Placeholder: "000000"},
			Alternatives: []ui.StepUpMethod{{Value: "password", Label: "Utiliser mon mot de passe"}}, CancelHref: "/settings/security",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func demoPolicySimulator() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var7 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var7 == nil {
			templ_7745c5c3_Var7 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = ui.PolicySimulator(ui.PolicySimulatorProps{
			ID: "demo-policy", Title: "Simulateur de politique", Description: "Interroger la même décision que la route protégée.",
			Action: "/security/policy/simulate", Target: "#demo-policy",
			Actors:    []ui.Option{{Value: "usr_42", Label: "Amélie Rousseau"}, {Value: "team_finance", Label: "Équipe Finance"}},
			Resources: []ui.Option{{Value: "account_acme", Label: "Compte Acme Caraïbes"}, {Value: "invoice_887", Label: "Facture FAC-887"}},
			Actions:   []ui.Option{{Value: "read", Label: "Consulter"}, {Value: "delete", Label: "Supprimer"}},
			Actor:     "usr_42", Resource: "account_acme", ActionValue: "delete", Context: "réseau externe",
			Simulation: &ui.PolicySimulation{DecisionID: "decision_4c12", Decision: ui.AccessDenied, Reason: "La suppression exige le rôle Administrateur sur ce compte.", Policy: "accounts.delete.v3", EvaluatedAt: "à 15:20:08", EvaluatedDatetime: "2026-08-25T15:20:08-04:00", Facts: []ui.PolicyFact{{Label: "Rôle effectif", Value: "Opérations"}, {Label: "Réseau", Value: "Externe"}}},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func demoSecurityEventFilters() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var8 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var8 == nil {
			templ_7745c5c3_Var8 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<form method=\"get\" action=\"/security/events\" up-submit up-target=\"#demo-security-events\" class=\"flex flex-wrap gap-2\"><label class=\"form-control min-w-44 flex-1\"><span class=\"sr-only\">Gravité</span><select name=\"severity\" class=\"select select-sm select-bordered\"><option>Toutes les gravités</option><option>Critique</option><option>À examiner</option></select></label> <label class=\"form-control min-w-44 flex-1\"><span class=\"sr-only\">Période</span><select name=\"period\" class=\"select select-sm select-bordered\"><option>Dernières 24 heures</option><option>7 derniers jours</option></select></label> <button type=\"submit\" class=\"btn btn-sm\">Filtrer</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func demoSecurityEventFeed() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var9 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var9 == nil {
			templ_7745c5c3_Var9 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = ui.SecurityEventFeed(ui.SecurityEventFeedProps{
			ID: "demo-security-events", Title: "Événements de sécurité", Description: "Projection filtrée pour l’équipe sécurité.", Filters: demoSecurityEventFilters(),
			Events: []ui.SecurityEvent{
				{ID: "evt_902", Title: "Échec répété de vérification", Summary: "5 codes incorrects pour un challenge de révocation globale.", Severity: ui.SecurityEventCritical, Actor: "amelie@acme.co", Target: "challenge_f912", IP: "198.51.100.18", OccurredAt: "il y a 3 minutes", Datetime: "2026-08-25T15:17:00-04:00", RequestID: "req_8f31", Href: "/security/events/902"},
				{ID: "evt_897", Title: "Permission directe accordée", Summary: "accounts:write sur Acme Caraïbes, expiration dans 6 jours.", Severity: ui.SecurityEventWarning, Actor: "nora@acme.co", Target: "amelie@acme.co", IP: "192.0.2.41", OccurredAt: "ce matin à 09:12", Datetime: "2026-08-25T09:12:00-04:00", RequestID: "req_7d02", Href: "/security/events/897"},
				{ID: "evt_881", Title: "Nouvelle session créée", Summary: "Connexion Safari Mobile avec authentification multifacteur.", Severity: ui.SecurityEventInfo, Actor: "amelie@acme.co", Target: "sess_phone", IP: "192.0.2.84", OccurredAt: "il y a 2 heures", Datetime: "2026-08-25T13:18:00-04:00", RequestID: "req_6aa4", Href: "/security/events/881"},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
