// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"strconv"
	"strings"
)

// MoneyProps renders an amount.
//
// Cents is minor units as an integer, never a float: 0.1 + 0.2 is not 0.3 in
// binary floating point, and money that drifts by a centime per operation is
// the oldest bug in commerce software.
type MoneyProps struct {
	Cents    int64
	Currency string // ISO 4217: "EUR", "USD", "JPY"
	Tone     string // optional semantic colour, e.g. "error" for a refund
	Sign     bool   // force a leading + on positive amounts
}

// minorUnits is the number of decimals a currency actually has. Assuming two
// turns ¥1000 into ¥10.00.
var minorUnits = map[string]int{
	"JPY": 0, "KRW": 0, "VND": 0, "CLP": 0, "ISK": 0,
	"BHD": 3, "KWD": 3, "OMR": 3, "TND": 3,
}

var currencySymbols = map[string]string{
	"EUR": "€", "USD": "$", "GBP": "£", "JPY": "¥", "CHF": "CHF",
}

func decimalsFor(currency string) int {
	if d, ok := minorUnits[strings.ToUpper(currency)]; ok {
		return d
	}
	return 2
}

func symbolFor(currency string) string {
	if s, ok := currencySymbols[strings.ToUpper(currency)]; ok {
		return s
	}
	return strings.ToUpper(currency)
}

// groupThousands inserts a no-break space every three digits, French style.
func groupThousands(digits string) string {
	var b strings.Builder
	for i, r := range digits {
		if i > 0 && (len(digits)-i)%3 == 0 {
			b.WriteString(" ")
		}
		b.WriteRune(r)
	}
	return b.String()
}

// FormatMoney renders minor units as a French-formatted amount.
// Pure and total: every int64 has an output, including the extremes.
func FormatMoney(cents int64, currency string) string {
	decimals := decimalsFor(currency)

	negative := cents < 0
	digits := strconv.FormatInt(cents, 10)
	if negative {
		digits = digits[1:] // FormatInt already wrote the sign
	}
	for len(digits) <= decimals {
		digits = "0" + digits
	}

	whole, frac := digits, ""
	if decimals > 0 {
		whole, frac = digits[:len(digits)-decimals], ","+digits[len(digits)-decimals:]
	}

	out := groupThousands(whole) + frac + " " + symbolFor(currency)
	if negative {
		return "−" + out // U+2212 minus, not a hyphen: it aligns with digits
	}
	return out
}

// Money renders an amount ready to sit in a column of amounts.
func Money(p MoneyProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		text := FormatMoney(p.Cents, p.Currency)
		if p.Sign && p.Cents > 0 {
			text = "+" + text
		}
		var templ_7745c5c3_Var2 = []any{"tabular-nums whitespace-nowrap", toneOf(p.Tone).Text}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<span class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/money.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(text)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/money.templ`, Line: 89, Col: 77}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
