// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020

package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// ThemeToggle switches between the configured light and dark daisyUI themes.
//
// Deux radios, pas une case à cocher : daisyUI compile `--prefersdark` en
// `@media (prefers-color-scheme: dark) { :root:not([data-theme]) { … } }`.
// Une case unique de valeur « dark » ne sait donc exprimer que « sombre » et
// « défaut » — et sur une machine dont le système est en sombre, « défaut »
// vaut sombre : la position « Clair » ne faisait rien. Deux radios posent
// chacune leur `:root:has(input.theme-controller[value=…]:checked)`, plus
// spécifique que le `:not([data-theme])` du média, donc les deux choix
// gagnent sur la préférence système.
//
// ponytail: aucune persistance — le choix vit dans le DOM, donc il survit aux
// échanges de fragments Unpoly (l'en-tête n'est pas remplacé) mais pas à un
// rechargement complet, qui repart de la préférence système. Pour le garder,
// il faut un cookie posé en POST et `[data-theme]` rendu sur `<html>` ; à
// écrire le jour où quelqu'un le demande.
func ThemeToggle(dark bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"join\" role=\"group\" aria-label=\"Thème\"><input type=\"radio\" name=\"theme\" value=\"light\" class=\"btn btn-sm join-item theme-controller\" aria-label=\"Clair\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !dark {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " checked")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "> <input type=\"radio\" name=\"theme\" value=\"dark\" class=\"btn btn-sm join-item theme-controller\" aria-label=\"Sombre\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if dark {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " checked")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
