// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020

package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"math"
	"time"
)

// TimestampProps renders one moment in time.
//
// Now is a parameter, never time.Now(): a component that reads the clock
// renders differently on every call and cannot be tested. The handler passes
// its own request time.
//
// Location is the operator's zone. A back-office that prints UTC while the
// operator reasons in local time produces confident wrong decisions, so the
// zone abbreviation is always shown, never implied.
type TimestampProps struct {
	At       time.Time
	Now      time.Time
	Location *time.Location
	Absolute bool // show the full date instead of the relative phrase
}

func (p TimestampProps) location() *time.Location {
	if p.Location != nil {
		return p.Location
	}
	return time.UTC
}

var relativeSteps = []struct {
	Below time.Duration
	Unit  time.Duration
	One   string
	Many  string
}{
	{45 * time.Second, 0, "", ""},
	{90 * time.Second, time.Minute, "minute", "minutes"},
	{45 * time.Minute, time.Minute, "minute", "minutes"},
	{90 * time.Minute, time.Hour, "heure", "heures"},
	{22 * time.Hour, time.Hour, "heure", "heures"},
	{36 * time.Hour, 24 * time.Hour, "jour", "jours"},
	{26 * 24 * time.Hour, 24 * time.Hour, "jour", "jours"},
	{45 * 24 * time.Hour, 30 * 24 * time.Hour, "mois", "mois"},
	{320 * 24 * time.Hour, 30 * 24 * time.Hour, "mois", "mois"},
}

// relativeTime phrases at relative to now. Pure: same inputs, same output.
func relativeTime(at, now time.Time) string {
	d := at.Sub(now)
	past := d < 0
	if past {
		d = -d
	}

	unit, one, many := 365*24*time.Hour, "an", "ans"
	for _, step := range relativeSteps {
		if d < step.Below {
			if step.Unit == 0 {
				return "à l'instant"
			}
			unit, one, many = step.Unit, step.One, step.Many
			break
		}
	}

	n := int(math.Round(float64(d) / float64(unit)))
	if n < 1 {
		n = 1
	}
	if past {
		return fmt.Sprintf("il y a %d %s", n, plural(n, one, many))
	}
	return fmt.Sprintf("dans %d %s", n, plural(n, one, many))
}

var frenchMonths = [...]string{
	"janvier", "février", "mars", "avril", "mai", "juin",
	"juillet", "août", "septembre", "octobre", "novembre", "décembre",
}

// absoluteTime spells the date out, with the zone abbreviation attached.
func absoluteTime(at time.Time, loc *time.Location) string {
	t := at.In(loc)
	zone, _ := t.Zone()
	return fmt.Sprintf("%d %s %d à %02d:%02d %s",
		t.Day(), frenchMonths[t.Month()-1], t.Year(), t.Hour(), t.Minute(), zone)
}

// Timestamp shows one phrasing and carries the other in its tooltip, so the
// exact moment is always one hover away and always machine-readable.
func Timestamp(p TimestampProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		absolute := absoluteTime(p.At, p.location())
		relative := relativeTime(p.At, p.Now)
		if p.Absolute {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<time datetime=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(p.At.Format(time.RFC3339))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/timestamp.templ`, Line: 97, Col: 44}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" title=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(relative)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/timestamp.templ`, Line: 97, Col: 63}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" class=\"tabular-nums\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(absolute)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/timestamp.templ`, Line: 97, Col: 97}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</time>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<time datetime=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue(p.At.Format(time.RFC3339))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/timestamp.templ`, Line: 99, Col: 44}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" title=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.ResolveAttributeValue(absolute)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/timestamp.templ`, Line: 99, Col: 63}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(relative)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/timestamp.templ`, Line: 99, Col: 76}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</time>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
